config/routes.rb
Rails.application.routes.draw do
  get 'homepage/personal'

  get 'homepage/experience'

  get 'homepage/interest'

  get 'homepage/activity'

  get 'homepage/ideas'

  root to: 'homepage#personal'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def personal
    @title = 'Benjamin Bao'
  end

  def experience
    @title = 'Experience'
  end

  def interest
    @title = 'Interest'
  end

  def activity
    @title = 'Activities'
  end

  def ideas
    @title = 'Ideas'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/activity.html.erb
<h1>Homepage#activity</h1>
<p>Find me in app/views/homepage/activity.html.erb</p>

app/views/homepage/experience.html.erb
<body>
  <div id='experienceWrapper'>
    <section class='experienceBLock'>
      <p class='experienceTitle'>Professional Internship</p>
      <ul class='experienceList'>
        <li class='experienceListTitle'>Project Intern - Project “Penguin” — SAP</li>
        <li class='experienceListBody'>Created and maintained roles and authorization in about 20 different stage and production system through SAP NetWeaver</li>
        <li class='experienceListBody'>Helped designing and analyzing the risks and conflicts of nearly 200 composite roles for CAH in project Penguin</li>
        <li class='experienceListBody'>Processed numbers of tickets and role requests by performing the role analysis and system simulations</li>

        <li class='experienceListTitle'>Web Developer Intern — SchooLinks Inc </li>
        <li class='experienceListBody'>Revamped the entire database structure with teammates by rebuilding the Entity-Relationship Diagram from scratch containing 5 main categories, 87 database tables with approximately 500 data fields .</li>
        <li class='experienceListBody'>Formulated a comprehensive Google SEO strategies by efficiently organizing the approximately 100 path names of web pages, speeding up the site loading time by employing techniques like “combining css”, “deferring javascript” etc, refining keyword searching (title, meta-tags and footer), and resolving crawl errors (including server errors, web page errors etc).</li>
        <li class='experienceListBody'>Created a 5-star-rating ranking algorithm (in php), which utilizes Wilson Confidence algorithm and eliminates outliers.</li>
        <li class='experienceListBody'>Designed and carried out 20 email templates through HTML and CSS, and implement them with Mandrill API in the back-end.</li>

        <li class='experienceListTitle'>Project Intern - Project “Engage” — English First (EF)</li>
        <li class='experienceListBody'>Wrote approximately 15 JSON files of teaching content and audio materials for the database of iPhone application “Engage”.</li>
        <li class='experienceListBody'>Participated in deciding the cloud server and whole database structure for iPhone application “Engage”.</li>
      </ul>
    </section>

    <section class='experienceBlock'>
      <p class='experienceTitle'>Startup & Entrepreneurship</p>
      <ul class='experienceList'>
        <li class='experienceListTitle'>Team Initiator/Technology Director - Project Hierarchy, UCLA Startup</li>
        <li class='experienceListBody'>Did both front-end design(UI and UX design) and back-end (users and databases) on the IOS application “Hierarchy”</li>
        <li class='experienceListBody'>Pitch the blueprint of project Hierarchy to UCLA Startup and got into the second round.</li>
        <li class='experienceListBody'>Wrote a 2000-line console application (in C++) to simulate the basketball ranking system, which ranks the basketball enthusiasts based on their statistics on court, and also provides functionalities including “Find a Match”, “Hall of Fame” etc.</li>
      </ul>
    </section>

    <section class='experienceBlock'>
      <p class='experienceTitle'>Other Internship & Researches</p>
      <ul class='experienceList'>
        <li class='experienceListTitle'>Corporate Culture Consulting Analyst - LONG Mandarin Co. </li>
        <li class='experienceListBody'>Researched the correlation between the Company Culture and profit with professor Eric Flamholtz from UCLA Anderson School of Management by fully understanding the documentation and constant email conversation.</li>
        <li class='experienceListBody'>Launched numbers of questionnaires and approximately 15 interviews with employees of all positions and extracted the data to calculate the correlation index between these two factors by using various statistical methods, like “regression analysis”.</li>

        <li class='experienceListTitle'>Optical Lab Assistant - Optical Lab of Zhongshan Hospital</li>
        <li class='experienceListBody'>Conducted a comprehensive experiment on Introcular Lens including testing and comparing the greyscale and resolution of 6 different kinds of Introcular Lens, and keep records of every data entry and show whether they are correlated.
        </li>
      </ul>
    </section>
  </div>
</body>

app/views/homepage/ideas.html.erb
<h1>Homepage#ideas</h1>
<p>Find me in app/views/homepage/ideas.html.erb</p>

app/views/homepage/interest.html.erb
<h1>Homepage#interest</h1>
<p>Find me in app/views/homepage/interest.html.erb</p>

app/views/homepage/personal.html.erb
<body>
	<div id='personalWrapper'>
		<section id='personalBasicInfo'>
			<canvas id='personalBasicInfoImage' width='400' height='400'>
				
			</canvas>

			<div id='personalBasicInfoText'>
				<ul>
					<li>Benjamin Bao</li>
					<li>University of California, Los Angeles</li>
					<li>10933 Rochester Ave, Apt 416</li>
					<li>Los Angeles, CA 90024</li>
					<li>Cell: 3109139124</li>
					<li>Email: byyagp@gmail.com</li>
				</ul>
			</div>
		</section>
		<section id='personalIntroductory'></section>
	</div>
</body>



<script>
		var c = document.getElementById("personalBasicInfoImage");
		var ctx = c.getContext("2d");
		var imageObj = new Image();
		imageObj.onload = function() {
        	ctx.drawImage(imageObj, 0, 0);
      	};
     	imageObj.src = 'profile.jpg';
</script>

app/views/layouts/application.html (Byy-PC's conflicted copy 2014-08-28).erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id='upperSiteMap'>
  </div>
  <div id='mainWrapper'>
  	<nav id='mainNav'>
  		<ul id='mainNavList'>
  			<li><%= link_to 'Personal', homepage_personal_path %></li>
  			<li><%= link_to 'Experience', homepage_experience_path %></li>
  			<li><%= link_to 'Ideas', homepage_ideas_path %></li>
  			<li><%= link_to 'Interest', homepage_interest_path %></li>
  			<li><%= link_to 'Activities', homepage_activity_path %></li>
  		</ul>
  	</nav>
    <%= yield %>
  </div>

  <div id='lowerSiteMap'>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='upperSiteMap'>
  </div>
  <div id='mainWrapper'>
  	<nav id='mainNav'>
  		<ul id='mainNavList'>
  			<li><%= link_to 'Personal', homepage_personal_path %></li>
  			<li><%= link_to 'Experience', homepage_experience_path %></li>
  			<li><%= link_to 'Ideas', homepage_ideas_path %></li>
  			<li><%= link_to 'Interest', homepage_interest_path %></li>
  			<li><%= link_to 'Activities', homepage_activity_path %></li>
  		</ul>
  	</nav>
    <%= yield %>
  </div>

  <div id='lowerSiteMap'>
  </div>
</body>
</html>